name: "[My Laravel App] Build and Deploy"

on:
  push:
    branches:
      - "main"
    paths:
      - 'my-laravel-app/**'
      - '.github/workflows/laravel-cicd.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    outputs:
      image_name: registry.digitalocean.com/my-registry123/my-laravel-app:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: docker
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd my-laravel-app
          docker build -t registry.digitalocean.com/my-registry123/my-laravel-app:${{ github.sha }} -f Dockerfile .
          docker push registry.digitalocean.com/my-registry123/my-laravel-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_REMOTE_PORT || '22' }} -r ./my-laravel-app/deploy/* ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:/opt/my-laravel-app/

      - name: Restart remote app
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} << 'EOF'
            cd /opt/my-laravel-app/
            yq -i '.services.web.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yml
            yq -i '.services.worker.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yml
            docker compose up -d --remove-orphans
          EOF
